services:
  app:
    build:
      context: .
    depends_on:
      - database
    ports:
      - 5000:5000
    environment:
      - APP_URL=http://127.0.0.1:5000
      - API_URI=/api/v1
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/postgres
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - UUID_SECRET1=${UUID_SECRET1}
      - UUID_SECRET2=${UUID_SECRET2}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - ./app:/usr/src/app
    restart: unless-stopped

  database:
    image: postgres:13
    hostname: database
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=postgres
